### ISSUE TITLE
stricter checking for 'system' variable

### ISSUE THREAD

**Issue by jastiso** [BassettLab/control_package#29]
A few of the functions that include a 'system' variable either don't have strict enough type checking, or throw unintuitive errors

ave_control() and get_control_inputs():
- if 'discrete' or 'continuous' is misspelled, the code will throw the error 'x referenced before assignment', which is not useful. 
- I think we should add an 'else' statement that throws an error that says something like 'incorrect system specification. please specify discrete or continuous'

matrix_normalization():
- the way the 'if/else' statement is structured, 'discrete' normalization is essentially the default.
- I think we should add an 'else' statement that is entered if 'system' is something unexpected, and throws a useful error (similar to above)

**Comment by lindenmp** [comment]
Thanks Jeni! I've implemented your suggestions and updated the unit tests. 

Now `ave_control()` `get_control_inputs()` and `matrix_normalization()` will all check for spelling mistakes in the `system` variable and throw a specific error. That error is now checked for in the unit tests
