### ISSUE TITLE
Something Wrong with the function get_control_inputs

### ISSUE THREAD

**Issue by WY-SHI** [BassettLab/control_package#33]
Hello, nctpy developers. When I set T=1 and system = "discrete", an error occurred in function `get_control_inputs`.
I debugged the code and found that it was in the `for` loop that the assignment dimensions of the M matrix did not match when i=1 (the last line in the following code).

```
    elif system == 'discrete':
        # Define joint state - costate matrix
        C = np.dot(-B, B.T) / (2 * rho)
        D = 2 * S
        I = np.eye(n_nodes)
        z = np.arange(n_nodes)

        # Construct system matrix
        M = np.zeros(((2 * T - 1) * n_nodes, (2 * T - 1) * n_nodes))

        # Constraints for the state equations
        for i in np.arange(T + 1):
            M[np.ix_(z + (i - 1) * n_nodes, z + (T - 2 + i) * n_nodes)] = -C
            if i != T:
                M[np.ix_(z + (i - 1) * n_nodes, z + (i - 1) * n_nodes)] = I
            if i != 0:
                M[np.ix_(z + (i - 0) * n_nodes, z + (i - 1) * n_nodes)] = -A_norm
```

**Comment by jastiso** [comment]
Thanks for using the tool and thanks for bringing the issue to our attention! I was able to recreate the bug you reported.

I noticed that later on the function sets a dimension to (T-2) when 'Constructing boundary condition vector'.  @lindenmp and @jk6294 do you think we should set the minimum T for discrete systems to 2? I can see that making sense

**Comment by lindenmp** [comment]
Yeah, this is known behavior. T can't be equal to 1 for discrete time systems, because then that's only 1 timepoint. I don't think we need to change the default, since `T=1` is reasonable for continuous systems. Instead, i think the better solution is to throw an error that explains T can't be 1 for discrete time systems.
